### PR TITLE
Track original VNodes to allow referential equality diff bypass

### PR DESCRIPTION
**Pull request by developit**
This improves scores on one of the benchmarks by more than 30%.

### CODE REVIEW

**Comment by developit** [comment]
Suspense tests are failing badly here, but nothing else.

**Comment by developit** [comment]
Paging @prateekbh - do you know of anything that would cause the Suspense implementation to rely on the diff always running against referentially-equal VNodes?

**Comment by cristianbote** [comment]
@developit do you feel this is ready? Are there any Suspense related issues left?

**Comment by prateekbh** [comment]
The failure in tests is consistent. I have no idea what is causing them

**Comment by developit** [comment]
Superseded by @JoviDeCroock's #2386.

**Pull request closed without merging**
