### PR TITLE
automated publishing workflow

### PR DESCRIPTION
**Pull request by JoviDeCroock**
This will automatically publish our new version to npm when we publish a release

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
Internal talk brought up a security concer, closing

**Comment by cecilemuller** [comment]
Was the concern that using a NPM token to publish lowers the security from two-factors to single-factor ?

**Comment by JoviDeCroock** [comment]
@cecilemuller One of the more important ones yes

**Comment by marvinhagemeister** [comment]
@cecilemuller yep, we require 2FA for everyone to be able to publish to npm and we're reluctant to turn that off. Nonetheless we'd really love to automate more of our release process. Not sure how though 🙈

**Comment by cecilemuller** [comment]
@marvinhagemeister I hear you, I do this step manually too because I refuse to remove the 2FA requirement, but I'm always on the lookout in case a solution emerges (that's even why I got curious when I saw the name of this PR).

**Comment by cecilemuller** [comment]
Now that [Github acquired NPM](https://github.blog/2020-03-16-npm-is-joining-github/), perhaps they will provide a safer way to publish packages in the future.

**Pull request closed without merging**
