### PR TITLE
Update Fake React Version

### PR DESCRIPTION
**Pull request by tim-on-github**
Per title : Update React Version

The included version is a bit old, this should be at least the end of the 16 Major line, or as I've put here, on 17.x

### CODE REVIEW

**Comment by tim-on-github** [comment]
The build and test looks to be blocked by something?

**Comment by marvinhagemeister** [comment]
> The build and test looks to be blocked by something?

Yeah it seems to be a new feature in GitHub. We have to check a box for first time contributors that we trust them to run the CI scripts.

**Review by marvinhagemeister — APPROVED** [review]
Awesome, thanks a bunch for making a PR 🙌

**Comment by tim-on-github** [comment]
No worries and thank you for merging!

**Comment by tim-on-github** [comment]
Actually quick question if I may @marvinhagemeister , would you know when this would likely be released?

**Pull request merged**
