### PR TITLE
Golf bytes

### PR DESCRIPTION
**Pull request by wizzardo**
moved typeof to separate function (-101B)

### CODE REVIEW

**Comment by wizzardo** [comment]
Interesting.. I compared js before compression

**Comment by JoviDeCroock** [comment]
gzip compression is based on recurring mentions. We always base our lost bytes minzipped. This can be seen by executing the `build` script.

**Comment by wizzardo** [comment]
Sorry, didn't know this detail, my target was to minimise raw js because browser needs to parse it every time, but js.gz can be cached

**Comment by wizzardo** [comment]
Ok, so please decline this pr as it's not relevant

**Comment by JoviDeCroock** [comment]
No problem, @wizzardo it was a fun exploration to see and thank you for spending your time trying this.

**Pull request closed without merging**
