### PR TITLE
Use Babel 7

### PR DESCRIPTION
**Pull request by hzoo**
not sure why the tests we're failing locally yet, so someone can take this pr and look into it!

### CODE REVIEW

**Comment by hassanbazzi** [comment]
I was gonna do this today and surprise y'all. Goddamn it hahaha

**Comment by hzoo** [comment]
@hassanbazzi test failed for me so you can still look into it 😄, I'm trying to upgrade some other projects atm anyway

**Comment by developit** [comment]
Seems like a bug in babel-preset-env?  It's encountering an exception in one of the transforms.

**Comment by xtuc** [comment]
It's an outdated version of `babel-traverse` but it works on my machine :thinking:
Are you caching `node_modules` in the build or something? Could you restart it?

**Comment by simonjoom** [comment]
i use preact  and babel 7 as well , the last alpha 7 is working, but didn't success to build my project with the version beta. maybe an issue from my install or from beta. i'm not sure

**Comment by xtuc** [comment]
What's your issue @simonjoom? Do you mind opening an issue on the Babel repo if it's on our side?

**Comment by simonjoom** [comment]
yes xtuc i ve got some issue with babel 7 but it's fixed by the new patches of babel 7 
one of them here: https://github.com/babel/babel/issues/6275 fixed problems

**Comment by marvinhagemeister** [comment]
The eslint config in `config/eslint-config.js` needs the following additional properties to fix the current error on CI:

```js
module.exports = {
  parserOptions: {
	ecmaVersion: 6,
	sourceType: 'module',
  }
}
```

The other linting errors are easy to fix, but I'm getting stuck on test failures in `PhantomJS`. I'm not sure what's causing these. Will investigate further.

**Comment by marvinhagemeister** [comment]
Found it! After a lot of digging through the compiled output, the failing tests are caused by a bug with how `babel 7` transforms the code.

The offending line is inside `diff()`:

```js
// Babel 7 (output trimmed for clarity)
exports.diffLevel = exports.mounts = void 0;
var diffLevel = 0;
exports.diffLevel = diffLevel;

function diff(dom, vnode, context, mountAll, parent, componentRoot) {
  var _old;
  if (!(_old = diffLevel, exports.diffLevel = diffLevel = _old + 1, _old)) {

  }

  exports.diffLevel = diffLevel = diffLevel - 1;

  // Here lies the issue:
  // The failing tests are caused by diffLevel unexpectedly counting upwards not
  // downwards. The original source for this line is:
  // 
  // if(!--diffLevel) {
  //
  // ...which is obviously quite a bit different from the line below:
  if (!(exports.diffLevel = diffLevel = diffLevel + 1)) {
    // ...snip
  }
}
```

Compare this against the output of with master:

```js
// Babel 6 (again, output is trimmed for clarity)
exports.diffLevel = exports.mounts = undefined;
var mounts = exports.mounts = [];
var diffLevel = exports.diffLevel = 0;

function diff(dom, vnode, context, mountAll, parent, componentRoot) {
  if (!(exports.diffLevel = diffLevel += 1, diffLevel - 1)) {
  
  }

  // Correct code: diffLevel counts downwards
  if (!(exports.diffLevel = diffLevel -= 1)) {
    // ...snip
  }
}
```

**Comment by marvinhagemeister** [comment]
[The PR](https://github.com/babel/babel/pull/7489) over at babeljs was just merged 🎉 Will work further on this once they make a new beta release 💯

**Comment by mkxml** [comment]
@marvinhagemeister Is this good to test again? Babel 7 is in beta 49 now.

**Comment by marvinhagemeister** [comment]
@mkxml Will try to find the time to check again the next days.

**Comment by k1r0s** [comment]
I skiped lint and tree failing tests

TODO: 
- fix lint 
- fix life cycle tests

**Comment by andrewiggins** [comment]
Preact master branch is using the latest and greatest from the Babel team 🎉, so I'm gonna go ahead and close this now :)

**Pull request closed without merging**
