### PR TITLE
Add LimeApp in real-world apps

### PR DESCRIPTION
**Pull request by gmarcos87**
LimeApp is a PWA written on preact and running on the LibreMesh nodes. LibreMesh is a custom firmeware to create mesh networks in a simple and self-administrable way.

### CODE REVIEW

**Comment by robertknight** [comment]
@gmarcos87 - The app failed to load when I looked just now. There was a Mixed Content error reported in the terminal. The URLs in this PR though are correct.

**Comment by gmarcos87** [comment]
Yes, the app is designed to work from http and embedded in a router with a particular firmeware. It is not visible from the web, maybe i should remove the link on github pages as it does not support http anymore.

**Comment by developit** [comment]
@gmarcos87 - would you be able to open a PR for the website repo instead of this one? If so that'd be great! Here's an example:
https://github.com/developit/preact-www/pull/289

**Comment by cristianbote** [comment]
Hey @gmarcos87 have you had a chance to open a PR against https://github.com/preactjs/preact-www?

**Pull request closed without merging**
