### PR TITLE
Handle setState in render

### LINKED ISSUE #2553: Preact-router and setState callback does not play nice
```
"preact": "^10.4.4",
"preact-router": "^3.2.1",
```

### Reproduction
Here is a minimal code to reproduce this issue.
https://codesandbox.io/s/compassionate-rgb-kl85q?file=/src/index.js

I am setting state with `this.setState` and reading it immediately in `setState` callback (second argument). See line # 13

### Steps to reproduce
- open console tab
- find console.log output from line # 14

### Expected Behavior
state should be `{ initial: true, handleRoute: true }`

### Actual Behavior
state is `{ initial: true }`

I can set state and read it immediately in `setState` callback in `componentDidMount` and other places but not in `preact-router`'s onChange callback.

### PR DESCRIPTION
**Pull request by jamesb3ll**
Fixes #2553

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
Hey is it possible to reproduce this in a test? If so let's add it to prevent us from regressing in this area

**Comment by marvinhagemeister** [comment]
Awesome thank you so much for the PR :+1: Let's add a test case for this like @JoviDeCroock suggested and than it's ready to be merged :tada:

**Comment by JoviDeCroock** [comment]
Awesome work, thank you so much!

**Comment by jamesb3ll** [comment]
Sorry, I've been busy the past few days. Hope the test I added is okay 😃 Thanks for the help!

**Comment by jamesb3ll** [comment]
Rebased master and squashed commits

**Pull request merged**
