### PR TITLE
(fix) - avoid stale closurses

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Problem here being I can't seem to reproduce this in a test :/

Fixes: https://github.com/preactjs/preact/issues/1998

Edit:
Shaves `-9B`

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
@JoviDeCroock is the comment about not being able to reproduce the issue in tests still relevant?

**Comment by JoviDeCroock** [comment]
@marvinhagemeister yes it is. I'm probably making a mistake somewhere ^^

**Comment by AlmeroSteyn** [comment]
Thank you for working on this! The effort and the tool is much appreciated.

**Comment by cristianbote** [comment]
Test case added -- it was a tricky one for sure

**Pull request merged**
