### PR TITLE
Remove unnecessary string concatenation

### PR DESCRIPTION
**Pull request by mhmdanas**

### CODE REVIEW

**Comment by developit** [comment]
This is specifically done to avoid the test harness and/or Babel modifying the symbol value.

**Comment by mhmdanas** [comment]
Since this string concatenation has a not so obvious purpose, wouldn't it be good to add a comment for later reference?

**Comment by marvinhagemeister** [comment]
Happy to accept PR's that add a comment here 👍

**Comment by mhmdanas** [comment]
Opened #2369 to add a clarification comment! :tada:

**Pull request closed without merging**
