### PR TITLE
Add types of `PictureInPictureEvent`

### PR DESCRIPTION
**Pull request by shoonia**
The `PictureInPictureEvent` interface represents picture-in-picture-related events, including
- [enterpictureinpicture](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/enterpictureinpicture_event)
- [leavepictureinpicture](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/leavepictureinpicture_event)
- [resize](https://developer.mozilla.org/en-US/docs/Web/API/PictureInPictureWindow/resize_event)

### CODE REVIEW

**Comment by shoonia** [comment]
TypeScript dom lib include `PictureInPictureEvent` interface 
https://github.com/microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#LL17374C1-L17383C3

**Comment by JoviDeCroock** [comment]
@shoonia you might need to upgrade our TypeScript version to 4.9 for `PictureInPictureEvent`

**Review by JoviDeCroock — APPROVED** [review]

**Comment by shoonia** [comment]
Thanks @JoviDeCroock

**Comment by JoviDeCroock** [comment]
@shoonia no problem, thank you for the PR! I will try to get this out tomorrow with #4011 don't have a lot of time left toda

**Pull request merged**
