### PR TITLE
Remove a duplicate test in render tests

### PR DESCRIPTION
**Pull request by OrKoN**
It looks like `should render nothing node given null` and `should not render null` are testing the same thing. Perhaps it's worth removing one of them. It might be that `scratch.childNodes` and `scratch.innerHTML` checks are not equivalent though, but they look the same to me.

### CODE REVIEW

**Comment by cristianbote** [comment]
Hey thanks for opening this PR. Well, we could argue that `render(null, scratch)` should be checked that it doesn't render anything and also that doesn't create empty children. Take this example:

```js
const div = document.createElement("div");
div.appendChild(document.createTextNode("")); // empty text node

div.innerHTML === ""; // true ✅ 
div.childNodes.length; // 1 <-- oops 🔴  
```
So, we still need that test case in order to properly handle the case were children could be created with empty text.

**Comment by ForsakenHarmony** [comment]
should we merge the tests then?

**Comment by cristianbote** [comment]
@ForsakenHarmony indeed! 😄 we could totally do that. @OrKoN are you ok with that? Would you like to (re)open the PR with both of the assertion in one case?

**Comment by OrKoN** [comment]
@cristianbote yes, it might be that also the 4 tests after `should not render null` might need to check for child nodes. What do you think?

P.S. I am on vacation now, will take a look in a week, greets from Italy!

**Comment by ForsakenHarmony** [comment]
Yeah enjoy your vacation first 🎉

**Pull request closed without merging**
