### PR TITLE
Fix access to undefined exception

### PR DESCRIPTION
**Pull request by billti**
Running some code locally and I was regularly hitting an error `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'is')`. I tracked it down to the line fixed in this PR. 

It would appear that sometimes `newVNode.props` may be undefined, so guarding against that.

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
Mind giving some way to reproduce this issue as props are defaulted to an object https://github.com/preactjs/preact/blob/main/src/create-element.js

**Comment by billti** [comment]
It was in the middle of a larger codebase and only happened sporadically, but I'll try and conjure up a minimal repo.

I assumed it could be null as a few lines later (427) it seems to check if it could have been null on the old node (via `oldProps = oldVNode.props || EMPTY_OBJ;`).

**Comment by JoviDeCroock** [comment]
A repro or test case would be needed either way so we can prevent regressions

**Comment by marvinhagemeister** [comment]
Took the liberty of updating the PR. The observed issue is a symptom of another cause in that recent refactors lead to invalid vnodes being passed to `createVNode`.

**Comment by billti** [comment]
Great! Thanks for the 'correct' fix, and super-fast turnaround. I love the project and use it whenever I can, so thanks for your work on it.

**Review by andrewiggins — APPROVED** [review]

**Pull request merged**
