### PR TITLE
fix: mac arm build

### PR DESCRIPTION
**Pull request by gengjiawen**
This internally bump `brotli-size`, the old version contains cpp module which not compatible on m1 mac.

The `d.ts` looks auto updated with microbundler update. Not sure should i revert it or leave it be.

### CODE REVIEW

**Review by JoviDeCroock — COMMENTED** [review]
This seems to change a bit more than just the brotli-size version, would it be worth just bumping brotli in our package json?

**Comment by rschristian** [comment]
Newer `microbundle` versions will generate `.d.ts` files if `"types"` is specified in the package file. Will need to run it with `--no-generateTypes` to ensure hand-written types aren't overwritten if brotli for some reason can't be bumped on its own.

**Comment by developit** [comment]
Good point @rschristian - @gengjiawen can you re-do this PR adding `--no-generateTypes` to each microbundle script?  The result should (hopefully) be a PR that only modifies `package.json` and `package-lock.json`.

**Comment by gengjiawen** [comment]
> Good point @rschristian - @gengjiawen can you re-do this PR adding `--no-generateTypes` to each microbundle script? The result should (hopefully) be a PR that only modifies `package.json` and `package-lock.json`.

done.

**Comment by rschristian** [comment]
Has the build size increased? We (unfortunately) don't seem to run compressed size action if the source hasn't been touched.

Last time I checked, updating Microbundle increased the output size by a non-negligible amount.

**Comment by gengjiawen** [comment]
Size not changed much 
on master
```
-rw-r--r-- 1 gitpod gitpod  10K Aug 30 02:05 preact.js
-rw-r--r-- 1 gitpod gitpod 9.9K Aug 30 02:04 preact.min.js
-rw-r--r-- 1 gitpod gitpod 9.9K Aug 30 02:04 preact.mjs
-rw-r--r-- 1 gitpod gitpod 9.9K Aug 30 02:04 preact.module.js
-rw-r--r-- 1 gitpod gitpod  11K Aug 30 02:04 preact.umd.js
```

on this patch

```
-rw-r--r-- 1 gitpod gitpod 9.9K Aug 30 01:44 preact.js
-rw-r--r-- 1 gitpod gitpod 9.9K Aug 30 01:44 preact.min.js
-rw-r--r-- 1 gitpod gitpod 9.9K Aug 30 01:44 preact.mjs
-rw-r--r-- 1 gitpod gitpod 9.9K Aug 30 01:44 preact.module.js
-rw-r--r-- 1 gitpod gitpod  11K Aug 30 01:44 preact.umd.js
```

**Comment by rschristian** [comment]
Rounding (or truncating) to the nearest 100b doesn't exactly give the clearest view. Probably doesn't make much sense to increase output size to solve a build-time platform compat issue.

Can `brotli-size` be upgraded independently as Jovi originally suggested? Microbundle will likely need to be updated at some point but, as it seems there are implications for doing so and it involves more moving pieces (pkg.exports, post-build scripts, etc), I'm not sure if it's worth touching to fix this specific issue if it can be avoided.

**Comment by JoviDeCroock** [comment]
The thing that scares me here is that this seems to be generating additional files 😅

**Review by marvinhagemeister — APPROVED** [review]
This is great! Thank you so much for taking the time to address feedback and hanging with us 👍 

@JoviDeCroock @rschristian The current iteration works fine for me and seems to generate the same output as before. I don't see any additional files being generated on my end.

**Comment by JoviDeCroock** [comment]
@marvinhagemeister generates an extra .mjs file for all packages, if that isn't an issue I am okay with merging

```
       1381 B: hooks.mjs.gz
       1277 B: hooks.mjs.br
```

**Comment by JoviDeCroock** [comment]
Want to do that in a follow-up or do we do that now? 😅

**Comment by marvinhagemeister** [comment]
I'm fine with a follow up. I think we dragged this PR long enough.

**Comment by rschristian** [comment]
The resulting `.mjs` files are Microbundle's modern builds, not the desired copy of `.module.js`. Will follow up.

**Comment by marvinhagemeister** [comment]
@rschristian oh, well in that case we should probably keep our script around. Currently it copies the `.module.js` file and overwrites `*.mjs` anyway.

**Comment by rschristian** [comment]
> @rschristian oh, well in that case we should probably keep our script around. Currently it copies the `.module.js` file and overwrites `*.mjs` anyway.

Made a PR but elected to disable the modern output. Figured relying on the overwrite would eventually trip someone up or create issues.

**Pull request merged**
