### PR TITLE
Add support for false value in aria-attributes

### PR DESCRIPTION
**Pull request by marvinhagemeister**
cc @robertknight

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
Please don't merge this yet. There are some things we should check first, mainly I'm worried that setting a falsey value to other aria attributes may not work as expected anymore.

**Comment by marvinhagemeister** [comment]
It looks to be a bit more involved as some aria attributes have a tristate value instead of plain booleans, like [aria-grabbed](https://www.w3.org/WAI/PF/aria-1.1/states_and_properties#aria-grabbed)

| Value | Description |
|---|---|
| false | Indicates that the element supports being dragged. |
| true | Indicates that the element has been "grabbed" for dragging. |
| undefined (default) | Indicates that the element does not support being dragged. |

**Comment by marvinhagemeister** [comment]
Ok, so I went through the spec and checked each attribute for more edge cases. There are none other than the one which lead to this PR where some attributes have three states. Attributes like `aria-checked` treat `false` as unchecked, whereas the attribute not being present is interpreted as `not-checkable`.

I also compared this with the behaviour present in React and they always stringify `false`, even if the aria attribute is not boolean like (e.g. `aria-labelledby`).

Therefor it should be safe for us too, to always stringify `false`.

**Comment by robertknight** [comment]
Wow, thanks for such a quick response on this @marvinhagemeister! The current `/^ar` regex works for [known HTML attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#Attribute_list) although it could cause unexpected results for new attributes in future, custom attributes or embedded markup (eg. SVG or MathML). I believe React always requires string values for unknown attribute names (and warns if you pass a boolean), so this might not be an issue.

**Comment by marvinhagemeister** [comment]
@robertknight I checked the current specs and for now the regex only matches aria attributes. If new ones are added to the spec we'll need to update it, for sure. With Custom Elements it get's more complex as they may theoretically also use something like `<foo-bar aria-custom-foo="whatever">`. I'm not sure how to satisfy everyone here :S

**Pull request merged**
