### PR TITLE
make jsx-runtime work when using an alias

### PR DESCRIPTION
**Pull request by JoviDeCroock**

### CODE REVIEW

**Review by developit — APPROVED** [review]
whoosh! totally hadn't thought of this one. we'll also need to update `@preactjs/compat`.

**Review by ForsakenHarmony — APPROVED** [review]

**Comment by rayriffy** [comment]
When this will be realesed in `preact`? I would love to use it with Next and React 17. 🧑‍🔬

**Comment by matthewkwong2** [comment]
> When this will be realesed in `preact`? I would love to use it with Next and React 17. 🧑‍🔬

Same, I'm wondering when will a stable release be available.

**Comment by shilangyu** [comment]
@JoviDeCroock does this actually work? This file does not seem to be included when installing preact:

image

So aliasing `react` to `preact/compat` makes `react/jsx-runtime` point to `preact/compat/jsx-runtime` which does not exist.

PS. yes, I am on the newly released version:


image

**Comment by marvinhagemeister** [comment]
@shilangyu Looks like we forgot to add them to our publish step. Made https://github.com/preactjs/preact/pull/2827 to address this. We'll cut a new release once that's merged.

**Pull request merged**
