### PR TITLE
Remove arguments warning for useMemo/useCallback hooks

### LINKED ISSUE #2758: [preact/debug] false positive complain about memoization
### Reproduction

Libraries:
- preact `10.4.8`

### Steps to reproduce

[Press here to see an example](https://github.com/framer/motion/blob/main/src/components/AnimatePresence/PresenceChild.tsx#L61).
Dynamic dependencies of memoized calculations through `useMemo/useCallback` result in a false positive complain about memoization.

Screen Shot 2020-09-19 at 5 13 31 AM

### Expected Behavior

Dynamic dependencies shouldn't result in a console's complain.

### Actual Behavior

False positive complain.

### PR DESCRIPTION
**Pull request by afzalsayed96**
Fixes #2758

### CODE REVIEW

**Review by JoviDeCroock — APPROVED** [review]
Thank you so much for the PR, sorry about the failed CI checks noise they aren't running for forks currently.

**Review by marvinhagemeister — APPROVED** [review]

**Comment by marco-koenen** [comment]
Hi all, when can I expect this PR to be merged into @preact/compat?

**Comment by marvinhagemeister** [comment]
@marco-koenen The `@preact/compat` package ist just a proxy package that imports everything from `preac  directly. So just need to update `preact` itself in your `package.json`.

**Comment by marco-koenen** [comment]
Ah perfect - makes sense! Thanks a lot.

**Pull request merged**
