### PR TITLE
Tag forwardRef & memo proxy components as React components in compat

### LINKED ISSUE #1824: [10.0.0-rc.0] Issue with forwardRef in material ui SwipeableDrawer
When creating a very basic app with just a render fn of:

```
                <SwipeableDrawer open={show_sidebar} onOpen={() => this.setState({ show_sidebar: true })} onClose={() => this.setState({ show_sidebar: false })}>
                    <Sidebar />
                </SwipeableDrawer>
```

based on latest material-ui I get the following issues with preact. If I switch to react it works fine with no errors

```
debug.module.js:2 Failed ForwardRef(Modal) type: Invalid ForwardRef(Modal) `children` supplied to `<ForwardRef(Modal) BackdropProps="[object Object]" BackdropComponent="function WithStyles(ForwardRef(Backdrop))() {}" className="MuiDrawer-root MuiDrawer-modal" open="true" onClose="function onClose() {}" ref="undefined" class="MuiDrawer-root MuiDrawer-modal" />`. Expected an element that can hold a ref. Did you accidentally use a plain function component for an element instead? For more information see https://material-ui.com/r/caveat-with-refs-guide
(anonymous) @ debug.module.js:2
preact__WEBPACK_IMPORTED_MODULE_0__.j.__b @ debug.module.js:2
preact__WEBPACK_IMPORTED_MODULE_0__.j.__b @ debug.module.js:2
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
T @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
A @ preact.module.js:13
setup_react @ main.js:63
(anonymous) @ main.js:83
main_setup @ main.js:81
(anonymous) @ main.js:93
./src/main.js @ main.js:8654
__webpack_require__ @ main.js:20
(anonymous) @ client:2
0 @ main.js:9223
__webpack_require__ @ main.js:20
(anonymous) @ main.js:84
(anonymous) @ main.js:87
Show 3 more frames
debug.module.js:2 Failed ForwardRef(Portal) type: The following props are not supported: `ref`. Please remove them.
(anonymous) @ debug.module.js:2
preact__WEBPACK_IMPORTED_MODULE_0__.j.__b @ debug.module.js:2
preact__WEBPACK_IMPORTED_MODULE_0__.j.__b @ debug.module.js:2
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
T @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
A @ preact.module.js:13
setup_react @ main.js:63
(anonymous) @ main.js:83
main_setup @ main.js:81
(anonymous) @ main.js:93
./src/main.js @ main.js:8654
__webpack_require__ @ main.js:20
(anonymous) @ client:2
0 @ main.js:9223
__webpack_require__ @ main.js:20
(anonymous) @ main.js:84
(anonymous) @ main.js:87
Show 5 more frames
debug.module.js:2 Failed ForwardRef(Slide) type: Invalid ForwardRef(Slide) `children` supplied to `<ForwardRef(Slide) in="true" direction="right" timeout="[object Object]" appear="false" role="document" tabIndex="-1" onEnter="function chainedFunction() {}" onExited="function chainedFunction() {}" ref="function () {}" />`. Expected an element that can hold a ref. Did you accidentally use a plain function component for an element instead? For more information see https://material-ui.com/r/caveat-with-refs-guide
(anonymous) @ debug.module.js:2
preact__WEBPACK_IMPORTED_MODULE_0__.j.__b @ debug.module.js:2
preact__WEBPACK_IMPORTED_MODULE_0__.j.__b @ debug.module.js:2
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
T @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
A @ preact.module.js:13
A @ compat.module.js:49
z @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
p.forceUpdate @ preact.module.js:13
w @ preact.module.js:13
Promise.then (async)
m @ preact.module.js:13
p.setState @ preact.module.js:13
preact__WEBPACK_IMPORTED_MODULE_0__.a.setState @ debug.module.js:2
o.__c.o.o @ hooks.module.js:13
(anonymous) @ Portal.js:41
E @ hooks.module.js:13
w @ hooks.module.js:13
preact__WEBPACK_IMPORTED_MODULE_0__.j.diffed @ hooks.module.js:13
preact__WEBPACK_IMPORTED_MODULE_0__.j.diffed @ debug.module.js:2
preact__WEBPACK_IMPORTED_MODULE_0__.j.diffed @ debug.module.js:2
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
T @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
g @ preact.module.js:13
P @ preact.module.js:13
A @ preact.module.js:13
setup_react @ main.js:63
(anonymous) @ main.js:83
main_setup @ main.js:81
(anonymous) @ main.js:93
./src/main.js @ main.js:8654
__webpack_require__ @ main.js:20
(anonymous) @ client:2
0 @ main.js:9223
__webpack_require__ @ main.js:20
(anonymous) @ main.js:84
(anonymous) @ main.js:87
Show 33 more frames
debug.module.js:2 Uncaught (in promise) TypeError: Cannot read property 'forEach' of null
    at preact__WEBPACK_IMPORTED_MODULE_0__.j.diffed (debug.module.js:2)
    at preact__WEBPACK_IMPORTED_MODULE_0__.j.diffed (debug.module.js:2)
    at P (preact.module.js:13)
    at g (preact.module.js:13)
    at P (preact.module.js:13)
    at p.forceUpdate (preact.module.js:13)
    at w (preact.module.js:13)
```

### PR DESCRIPTION
**Pull request by developit**
This should fix #1824.

### CODE REVIEW

**Comment by developit** [comment]
Repro with inlined version of this fix showing it works:
https://codesandbox.io/s/issue-1824-1sjge

**Comment by JoviDeCroock** [comment]
Hmm, we might want to add a test for this

**Comment by developit** [comment]
Agreed. My fear was that there are more cases where we need to do this. TBH I'm not actually sure MUI's expectations are correct here, but it's impossible to fix on our end without doing this.

@JoviDeCroock I wasn't sure whether we should consider also moving `._forwarded` to the prototype. It's shared and only a Boolean, but maybe worth it?

**Comment by marvinhagemeister** [comment]
Not sure about moving `_forwarded` onto the prototype. Right now it's an internal thing and the devtools relies on it to detect the component type.

**Pull request merged**
